Feature/ft 17 sql delight
VitalyPeryatin/FinanceTracker pull request #11
Opened 2022-09-04 16:31 UTC by vitaliyche

2022-09-04 18:42 UTC, VitalyPeryatin requested changes

2022-09-04 18:42 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +android {
Актуализируй код из ветки `develop` и сделай PR в ветку `develop`. В `main` мы не сливаем feature ветки

2022-09-05 15:21 UTC, Bittner322 requested changes
Полностью согласен с Виталием

2022-09-05 15:29 UTC, grafgad commented on app/build.gradle.kts
> +
Я новые библиотеки подключаю сверху. Виталий как правильнее?

2022-09-06 04:26 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +
Без разницы, можно даже в середину подключать. Обычно сверху более крупные, более основные библиотеки (core, compose), а снизу более второстепенные (coil, gson)

2022-09-06 08:33 UTC, closed without merging