feature/FT-13_main_tabs
VitalyPeryatin/FinanceTracker pull request #12
Opened 2022-09-05 16:44 UTC by grafgad

2022-09-06 04:38 UTC, VitalyPeryatin requested changes

2022-09-06 04:38 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/MainActivity.kt
> +            NavigationItem.Else
`NavigationItem.More`

2022-09-06 04:38 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/MainActivity.kt
> +                unselectedContentColor = Color.White.copy(0.4f),
Не пиши числа без именованных аргументов, если из контекста нельзя точно сказать, что означает это число. Тут нужно добавить именованный аргумент "alpha = "

2022-09-06 04:38 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/NavigationItem.kt
> +        iconRes = R.drawable.ic_else,
`R.drawable.ic_more`

2022-09-06 04:38 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/NavigationItem.kt
> +        title = "Главная"
Строки не хардкодим, только через ресурсы

2022-09-06 04:38 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/sreens/container/Container.kt
> +
Лишняя пустая строка

2022-09-06 04:38 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/sreens/container/Container.kt
> +fun Navigation(
`private fun`

2022-09-06 04:38 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/sreens/container/Container.kt
> +fun Navigation(
`Navigation` -> `TabNavigation`

2022-09-06 04:38 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/MainActivity.kt
> +            CoinTheme (){
Лишние фигурные скобки

2022-09-06 04:38 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/MainActivity.kt
> +                    color = MaterialTheme.colors.background
Если уже есть CoinTheme, то лучше везде доставать цвета из нее, а не из `MaterialTheme.colors` или из `Colors`

2022-09-06 04:38 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/theme/Typograph.kt
> +val Typography = Typography(
Опечатка в названии файла: `Typography`

2022-09-06 21:47 UTC, grafgad commented on app/src/main/java/com/finance_tracker/finance_tracker/NavigationItem.kt
> +        title = "Главная"
не могу понять как вытащить само значение и отобразить

2022-09-06 21:50 UTC, grafgad commented on app/src/main/java/com/finance_tracker/finance_tracker/MainActivity.kt
> +                    color = MaterialTheme.colors.background
У меня не получается. Во всех руководствах все из MaterialTheme вытаскивают. Как это сделать?

2022-09-10 16:12 UTC, VitalyPeryatin requested changes

2022-09-10 16:12 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/MainActivity.kt
> +                    color = CoinTheme.color.background//MaterialTheme.colors.background
Убери комментарий `//MaterialTheme.colors.background`

2022-09-10 16:12 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/NavigationItem.kt
> +        route = R.string.main,
`route` это строка, которая фигурирует только внутри программы, поэтому эта строка должна быть вынесена в константы, а не в strings.xml. В данном случае route можно даже не выносить в константы, так как это лишний раз усложнит программу. Оставь здесь просто обычную строку. Можно в данном случае захардкодить строку. Остальное все правильно сделал. То, что видит пользователь вынесено в xml

2022-09-10 16:12 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/theme/CoinTypography.kt
> +//val Typography = Typography(
Закомментированного кода в PR никогда не должно быть

2022-09-10 16:12 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/theme/CoinTypography.kt
> +data class CustomTypography(
В данном случае больше подходит название `CoinTypography`

2022-09-10 16:33 UTC, VitalyPeryatin approved these changes

2022-09-10 16:34 UTC, Bittner322 approved these changes

2022-09-10 16:40 UTC, merged