FT-22: Подготовил таблицу и API для добавления транзакций
VitalyPeryatin/FinanceTracker pull request #15
Opened 2022-09-08 14:23 UTC by vitaliyche

Создал таблицу Transactions с полями
id
amount
category
date

Реализовал для таблицы CRUD операции

2022-09-09 05:55 UTC, VitalyPeryatin requested changes

2022-09-09 05:55 UTC, VitalyPeryatin commented on app/src/main/sqldelight/com/finance_tracker/finance_tracker/AppDatabase.sq
> +CREATE TABLE transactionsEntity (
Названия таблиц обычно пишутся с большой буквы

2022-09-09 05:55 UTC, VitalyPeryatin commented on app/src/main/sqldelight/com/finance_tracker/finance_tracker/AppDatabase.sq
> +    id INTEGER NOT NULL PRIMARY KEY,
А не получится ли ещё добавить авто генерируемое id?

2022-09-09 05:55 UTC, VitalyPeryatin commented on app/src/main/sqldelight/com/finance_tracker/finance_tracker/AppDatabase.sq
> +    amount INTEGER NOT NULL,
Здесь скорее всего нужен тип с плавающей запятой. Причем стоит помнить, что в двоичной системе счисления числа с плавающей запятой очень относительны и могут не соответствовать предполагаемым значениеям в десятичной системе счисления. Поэтому погугли какой лучше всего тип подходит здесь. 
Есть DECIMAL, NUMERIC, REAL и так далее

2022-09-09 05:55 UTC, VitalyPeryatin commented on app/src/main/sqldelight/com/finance_tracker/finance_tracker/AppDatabase.sq
> +    date TEXT NOT NULL
Дата должна храниться либо как число, либо как дата (лучше второе), так как это позволит легко сортировать записи. Никогда не надо зранить дату в виде строки. Особенно в БД

2022-09-09 05:55 UTC, VitalyPeryatin commented on app/src/main/sqldelight/com/finance_tracker/finance_tracker/AppDatabase.sq
> +    category TEXT NOT NULL,
`category` может быть nullable

2022-09-10 13:36 UTC, grafgad commented on app/src/main/sqldelight/com/finance_tracker/finance_tracker/AppDatabase.sq
> +    date TEXT NOT NULL
Речь идет о timestamp или дату как-то еще хранят?

2022-09-10 16:00 UTC, VitalyPeryatin commented on app/src/main/sqldelight/com/finance_tracker/finance_tracker/AppDatabase.sq
> +    date TEXT NOT NULL
Да, под капотом она хранится как timestamp всегда, но бывает, что некоторые БД предоставляют такие типы данных как DATE, тогда можно прямо в DATE удобно сохранять

2022-09-12 21:51 UTC, grafgad requested changes

2022-09-12 21:51 UTC, grafgad commented on app/src/main/sqldelight/com/finance_tracker/finance_tracker/AppDatabase.sq
> +    date TEXT NOT NULL
Что ты посоветуешь Виталию? Я так понимаю DATE.

2022-09-13 05:49 UTC, VitalyPeryatin commented on app/src/main/sqldelight/com/finance_tracker/finance_tracker/AppDatabase.sq
> +    date TEXT NOT NULL
В идеале бы Date, но так как его нет в SQLite похоже, то я бы рекомендовал использовать INTEGER, и хранить timestamp 
<img width="748" alt="image" src="https://user-images.githubusercontent.com/22561563/189819735-46178d0e-e6d4-4c8f-8665-b6d434e24966.png">

2022-09-13 21:40 UTC, grafgad approved these changes

2022-09-14 08:07 UTC, VitalyPeryatin approved these changes

2022-09-14 08:08 UTC, merged