Изменил иконку приложения
VitalyPeryatin/FinanceTracker pull request #18
Opened 2022-09-10 18:30 UTC by grafgad

FT-18
Изменил иконку

2022-09-10 19:54 UTC, Bittner322 approved these changes

2022-09-11 05:49 UTC, VitalyPeryatin requested changes

2022-09-11 05:49 UTC, VitalyPeryatin commented on app/src/main/res/drawable/ic_launcher_foreground.xml
> +  <group android:scaleX="0.3323077"
А зачем уделять webp иконки из `mipmap-dpi` папок? Надо было заменить эти иконки на актуальные. На версиях ниже 26 они либо вообще не прорисуются, либо прорисуются в очень плохом качестве

2022-09-11 07:38 UTC, grafgad commented on app/src/main/res/drawable/ic_launcher_foreground.xml
> +  <group android:scaleX="0.3323077"
Они сами удалились... Я еще раз все переделал, и иконки в этих папках остались старыми, они не изменились. Это нормально?

2022-09-11 08:19 UTC, VitalyPeryatin commented on app/src/main/res/drawable/ic_launcher_foreground.xml
> +  <group android:scaleX="0.3323077"
Очень странно. А попробуй удалить вообще все старые иконку и ресурсы старых иконков. И с нуля через Image Asset создать иконку

2022-09-11 22:44 UTC, grafgad commented on app/src/main/res/drawable/ic_launcher_foreground.xml
> +  <group android:scaleX="0.3323077"
![image](https://user-images.githubusercontent.com/78178266/189551995-89601b2e-2ded-42a5-a578-db31a8ef3edf.png)
Удалил и заново залил. Теперь пустые папки v24 и anydpi-v26. Остальные иконки поменялись и соответствуют.

2022-09-13 05:44 UTC, VitalyPeryatin commented on app/src/main/res/drawable/ic_launcher_foreground.xml
> +  <group android:scaleX="0.3323077"
`drawable-v24` в нашем случае не нужен, так как у нас и так 24 API - минимальный. А вот `mipmap-anydpi-v26` нужен. Его скорее всего можно было не удалять скорее всего, так как в нем ничего не поменялось бы. В остальном - все правильно

2022-09-13 19:07 UTC, VitalyPeryatin approved these changes

2022-09-13 19:07 UTC, VitalyPeryatin commented on app/src/main/res/drawable/ic_launcher_foreground.xml
> +  <group android:scaleX="0.3323077"
Пропали файлы в `mipmap-anydpi-v26`. Нужно восстановить

2022-09-13 19:20 UTC, grafgad commented on app/src/main/res/drawable/ic_launcher_foreground.xml
> +  <group android:scaleX="0.3323077"
Эти файлы автоматически удаляются...
Сейчас еще раз попробую.

2022-09-13 19:31 UTC, closed without merging