FT-33: Реализовать раздел My Accounts
VitalyPeryatin/FinanceTracker pull request #32
Opened 2022-10-12 12:47 UTC by Bittner322

Реализовал экран My accounts, самая начальная стадия

2022-10-13 02:04 UTC, productomar commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
Поправьте меня, если я не прав, но тут лишний пробел?

2022-10-13 02:15 UTC, productomar requested changes

2022-10-13 02:15 UTC, productomar commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
>  package com.finance_tracker.finance_tracker.presentation.accounts
Мне кажется, что необходимо было сделать работу по следующему пути: app/src/main/java/com/finance_tracker/finance_tracker/presentation/**Home**/MyAccounts.kt

app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts - это отдельный экран у нас и, предполагаю, данная папка именно для него.
![image](https://user-images.githubusercontent.com/99362820/195482560-2954dc4e-ee82-4f63-beba-2ac4afbb4cb7.png)

2022-10-13 02:15 UTC, productomar commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
> +@Composable
Не могу отделаться от ощущения, что Composable и Preview необходимо было вынести в отдельный файл. Возможно, я не прав, но почему хочется вынести это в файл Account Card.

2022-10-13 07:23 UTC, Bittner322 commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
>  package com.finance_tracker.finance_tracker.presentation.accounts
Мне кажется ты ошибаешься. В разделе presentation делается вроде как отдельный package для каждого экрана, там не нужно все в одну директорию ссыпать

2022-10-13 07:23 UTC, Bittner322 commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
Ты прав

2022-10-13 07:24 UTC, Bittner322 commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
> +@Composable
Это нужно уточнить у Виталия

2022-10-13 18:41 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
>  package com.finance_tracker.finance_tracker.presentation.accounts
@productomar 
Миша все правильно сделал. Каждый фиче-экран всегда лежит в своей фиче-папке. Если бы Миша работал над экраном таба Home, то внутри папки `home` писал бы код. А Миша работал над списком счетов таба Accounts. Это другая фича, и соответственно в папке `accounts` её надо было реализовывать

2022-10-13 18:50 UTC, VitalyPeryatin requested changes

2022-10-13 18:50 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
> +@Composable
Все верно! 
Все что можно переиспользовать в рамках приложения - нужно выносить в отдельный файл по возможности. В данном случае эта карточка будет использоваться на 2-х экранах: на списке счетов таба Accounts, и на главном экране в том же списке счетов. В идеале я бы вынес бы этот компонент даже в `core`/`ui` отдельным файлом со своей превьюшкой

2022-10-13 18:50 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
> +            Icon(painter = painterResource(R.drawable.ic_wallet_active),
Не забывай тут и в других местах о форматировании: каждый именованный параметр с новой строки, если параметра больше 1-го

2022-10-13 18:50 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
> +                contentDescription = "Credit card icon",
Давай пока `contentDescription` везде оставлять `null`. Пока нам будет весьма затруднительно везде его поддерживать, весьма долго.

2022-10-13 18:50 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
> +                modifier = modifier
modifier переиспользуемый из параметров (тот, что с маленькой буквы у тебя написан как раз), может быть ТОЛЬКО у корневой функции внутри тела твоей функции. Во всех остальных вложенных функциях вызывается Modifier по умолчанию (то есть `Modifier` с большой буквы)

2022-10-13 18:50 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
> +                fontSize = 12.sp,
Не указывай fontSize, это менее гибко. Лучше использоуй параметр `style` у текста. И ему в качестве значения передавай нужный `CoinTheme.typography`

2022-10-13 18:50 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
> +                color = Color.White.copy(alpha = 0.5f),
Все цвета стараемся использовать только из `CoinTheme.colors`, так как это позволяет более гибко работать с темами светлая/темная

2022-10-14 03:33 UTC, productomar commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsScreen.kt
>  package com.finance_tracker.finance_tracker.presentation.accounts
Окей, я почему-то думал, что работа идет над виджетом на экране `Home`. Вот поэтому важно прикладывать скриншот результата :)

2022-10-14 18:39 UTC, VitalyPeryatin requested changes

2022-10-14 18:39 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
> +            .height(128.dp)
Упрощай код. Зачем использовать 2 модифаера, если можно использовать один: `.size(width = 160.dp, height =  128.dp)`. 
Но в данном случае ширина карточки должна быть гибкой, так как на разных экранах это будет разное кол-во dp.

2022-10-14 18:39 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
> +                    .height(29.dp)
В данном случае лучше просто `.size(29.dp)` заиспользовать

2022-10-14 18:39 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
> +                contentDescription = "",
`contentDescription = null`

2022-10-14 18:39 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
> +                tint = Color.White
`CoinTheme`

2022-10-14 18:39 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsAppBar.kt
> +                tint = Color(0xFF009BFF)
`CoinTheme`

2022-10-15 07:27 UTC, VitalyPeryatin approved these changes

2022-10-15 07:27 UTC, merged