FT-40: Реализовать виджет счетов на экране "Home"
VitalyPeryatin/FinanceTracker pull request #33
Opened 2022-10-14 18:02 UTC by Bittner322

Реализовал виджет счетов на экране "Home"

2022-10-15 07:55 UTC, productomar approved these changes

2022-10-15 18:37 UTC, VitalyPeryatin requested changes

2022-10-15 18:37 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
> +            .width(160.dp),
`.size`

2022-10-15 18:37 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
> +                contentDescription = "",
`contentDescription = null`

2022-10-15 18:37 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
> +                    .width(29.dp),
`.size`

2022-10-15 18:37 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
> +                tint = Color.White
`CoinTheme.color`

2022-10-15 18:37 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/accounts/AccountsAppBar.kt
> +                tint = Color(0xFF009BFF)
`CoinTheme.color`

2022-10-15 18:37 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/home/MyAccountsHeader.kt
> +fun myAccountsHeader() {
Composable функции всегда пишутся с большой буквы

2022-10-15 18:37 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/home/MyAccountsHeader.kt
> +fun myAccountsHeader() {
Забыл про обязательный первый параметр-Modifier в Composable фнукции

2022-10-15 18:37 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/home/MyAccountsHeader.kt
> +            painter = painterResource(id = R.drawable.ic_arrow_next_small),
Давай везде писать в одном стиле: без именованного параметра `id` для `painterResource`, так как для этой функции параметр очевиден

2022-10-15 18:37 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/presentation/home/MyAccountsHeader.kt
> +fun myAccountsHeaderPreview() {
Функция с большой буквы

2022-10-16 07:46 UTC, VitalyPeryatin requested changes

2022-10-16 07:46 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
> +            .height(128.dp)
`.size`

2022-10-16 08:07 UTC, VitalyPeryatin approved these changes

2022-10-16 08:07 UTC, merged