FT-44: Реализовать CI/CD через GitHubActions
VitalyPeryatin/FinanceTracker pull request #38
Opened 2022-10-17 12:03 UTC by Bittner322

Самая начальная версия.

2022-10-17 16:09 UTC, VitalyPeryatin requested changes

2022-10-17 16:09 UTC, VitalyPeryatin commented on .github/workflows/android.yml
> +    - name: Create file
А не получится ли не создавать отдельно пустой файл? Может без этой строки кода получится обойтись?

2022-10-17 16:09 UTC, VitalyPeryatin commented on .github/workflows/android.yml
> +      run: ./gradlew build
Давай пока использовать команду `./gradlew assembleDebug`. Она будет работать ощутимо быстрее. Во-первых нам не надо под юнит тестирование собирать сборку, во вторых нам достаточно собрать только Debug сборку, а не Debug + Release.

2022-10-17 16:58 UTC, VitalyPeryatin requested changes

2022-10-17 16:58 UTC, VitalyPeryatin commented on .github/workflows/android.yml
> +    - name: Grant execute permission for gradlew
Теперь надо сделать так, чтобы сборка на GitHub успешно скомпилировалось. Пока компиляция проходит с ошибкой. Говорит, что нет файла. Во вкладке Checks можешь посмотреть в чем ошибка 
<img width="706" alt="image" src="https://user-images.githubusercontent.com/22561563/196238274-a91e901d-a897-4b1f-8c19-34d890f1e4e3.png">

2022-10-17 17:04 UTC, Bittner322 commented on .github/workflows/android.yml
> +    - name: Grant execute permission for gradlew
Поменял app на android и все прошло, не знаю соберет или нет

2022-10-18 18:47 UTC, VitalyPeryatin approved these changes

2022-10-18 18:47 UTC, merged