FT-7: Добавил LeakCanary
VitalyPeryatin/FinanceTracker pull request #4
Opened 2022-08-28 18:22 UTC by Bittner322

2022-08-29 04:00 UTC, VitalyPeryatin requested changes

2022-08-29 04:00 UTC, VitalyPeryatin commented on app/build.gradle
> +    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.9.1'
Не забывай актуализировать статусы задач в Jira! Это важно

2022-08-30 10:21 UTC, vitaliyche approved these changes

2022-08-30 11:02 UTC, VitalyPeryatin commented on build.gradle
> +        agp_version = '7.3.0-rc01'
Зачем выносить `agp_version` в `ext`?

2022-08-30 11:03 UTC, VitalyPeryatin requested changes

2022-08-30 11:03 UTC, VitalyPeryatin commented on build.gradle
> +        agp_version = '7.3.0-rc01'
Зачем выносить `agp_version` в `ext`?

2022-08-30 11:06 UTC, Bittner322 commented on build.gradle
> +        agp_version = '7.3.0-rc01'
Я не знаю что это, оно само так появилось после установки бета версии студии.

2022-08-30 11:07 UTC, VitalyPeryatin commented on build.gradle
> +        agp_version = '7.3.0-rc01'
Тогда удали `ext`

2022-08-30 16:30 UTC, productomar approved these changes
Узнал, что такое Garbage Collector и как подключается LeakCanary

2022-08-30 19:23 UTC, grafgad requested changes

2022-08-31 09:43 UTC, VitalyPeryatin commented on build.gradle
> +        agp_version = '7.3.0-rc01'
Жду удаления `ext` блока)

2022-09-01 16:05 UTC, VitalyPeryatin approved these changes

2022-09-01 18:28 UTC, grafgad approved these changes

2022-09-01 18:36 UTC, vitaliyche approved these changes
Гуд. Но по-моему Виталик мне говорил, что лучше использовать одинарные кавычки, вместо двойных. Заодно и скобки будут не нужны. На пару символов в коде меньше станет)

2022-09-01 18:37 UTC, Bittner322 commented
> Гуд. Но по-моему Виталик мне говорил, что лучше использовать одинарные кавычки, вместо двойных. Заодно и скобки будут не нужны. На пару символов в коде меньше станет)

Так тут kts)

2022-09-01 18:41 UTC, VitalyPeryatin commented
> Гуд. Но по-моему Виталик мне говорил, что лучше использовать одинарные кавычки, вместо двойных. Заодно и скобки будут не нужны. На пару символов в коде меньше станет)

Возможно, я оговорился. Всегда говорил, что двойные кавычки предпочтительнее одинарных, так как в двойные кавычки можно добавлять переменные. А ещё тут не классический gradle, а gradle.kts, поэтому двойные кавычки и круглые скобки тут обязательны

2022-09-01 18:49 UTC, vitaliyche commented
> kts

Упс. Не заметил)

2022-09-01 19:29 UTC, merged