FT-41: Добавил экран настроек категорий
VitalyPeryatin/FinanceTracker pull request #43
Opened 2022-10-20 14:11 UTC by Bittner322

Самая начальная и очень сырая версия

2022-10-20 17:10 UTC, VitalyPeryatin requested changes

2022-10-20 17:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategoryCard.kt
> +                width = 296.dp,
Чет я сомневаюсь что здесь нужны точная высота и ширина. Это очень редкий кейс, когда можно воспользоваться этим модифаером. А уж тем более если внутри содержится текст, то с вероятностью 99% ограничивать единым числом высоту и ширину не стоит

2022-10-20 17:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategoryCard.kt
> +                .align(Alignment.CenterVertically)
`tint` потерялся

2022-10-20 17:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategoryCard.kt
> +                .size(9.dp)
`.size(8.dp)`
Даже если в дизайне указаны размеры не кратные 4-м в Android лучше указывать размеры кратные 4-м. Это негласное правило Android дизайна. Дизайнеры о нем знают, но иногда забывают про него

2022-10-20 17:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategorySettingsAppBar.kt
> +
Лишние пустые строки

2022-10-20 17:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategorySettingsAppBar.kt
> +@TabNavGraph
Здесь точно нужна `@TabNavGraph` аннотация?

2022-10-20 17:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategorySettingsScreen.kt
> +@TabNavGraph
Тут скорее всего нужна аннотация `@RootNavGraph`, так как экран должен открываться поверх табов

2022-10-20 17:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategorySettingsScreen.kt
> +                    start = 19.dp
`dp` кратное 4-м

2022-10-20 17:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategorySettingsScreenViewModel.kt
> +        getCategoriesFromDatabase()
Уже не первый раз говорю: в названии метод `get` может использоваться только если метод возвращает какие-то данные и не выполняет под собой сложную логику. Здесь `get` не подходит в качестве префикса. Также во ViewModel не должно быть информации о том откуда загрузили данные: из БД или из сети. Об этом должен знать только Repository. 

Так что метод лучше назвать `loadAllCategories()`

2022-10-20 17:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategorySettingsTabs.kt
> +            .padding(horizontal = 7.dp, vertical = 8.dp),
`dp` кратное 4-м

2022-10-20 17:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategorySettingsTabs.kt
> +            Color.Black
Цвета берем из `CoinTheme`

2022-10-20 17:12 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/repositories/CategoryRepository.kt
> +class CategoryRepository(
Лучше называй репозитории так, чтобы сущность была во множественном числе: `CategoriesRepository`

2022-10-21 14:18 UTC, Bittner322 commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategorySettingsScreen.kt
> +@TabNavGraph
Поставил RootNavGraph, вылетает

2022-10-21 14:20 UTC, Bittner322 commented
<img width="352" alt="Снимок экрана 2022-10-21 в 20 17 11" src="https://user-images.githubusercontent.com/100136541/197218279-9c10165b-894d-4d96-811c-a69dd00ae044.png">
Так выглядит экран сейчас

2022-10-22 10:10 UTC, VitalyPeryatin commented on android/src/main/kotlin/com/finance_tracker/finance_tracker/presentation/categories/CategorySettingsScreen.kt
> +@TabNavGraph
Сейчас вольем изменения с Odyssey и можно вообще избавиться от аннотаций `TabNavGraph` и `Destination`

2022-10-22 13:34 UTC, closed without merging