Feature/ft 8 add detekt
VitalyPeryatin/FinanceTracker pull request #5
Opened 2022-08-29 18:59 UTC by Bittner322

FT-8: Добавил Detekt

2022-08-29 19:29 UTC, grafgad commented on build.gradle
> +    id "io.gitlab.arturbosch.detekt" version "1.21.0"
для kts надо так:
id("io.gitlab.arturbosch.detekt") version "1.21.0"

2022-08-29 21:06 UTC, grafgad commented on app/build.gradle
> +    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.9.1'
для kts надо так:
debugImplementation("com.squareup.leakcanary:leakcanary-android:2.9.1")

2022-08-29 21:07 UTC, grafgad commented on app/build.gradle
> +    id "io.gitlab.arturbosch.detekt"
для kts надо так:
id ("io.gitlab.arturbosch.detekt")

2022-08-29 21:08 UTC, grafgad requested changes

2022-08-29 21:08 UTC, grafgad commented on app/build.gradle
> +    id "io.gitlab.arturbosch.detekt"
для kts надо так:
id ("io.gitlab.arturbosch.detekt")

2022-08-30 10:31 UTC, vitaliyche approved these changes

2022-08-30 11:01 UTC, VitalyPeryatin requested changes
Все PRы направляются только в ветку `develop`

2022-08-30 11:10 UTC, VitalyPeryatin requested changes

2022-08-30 11:10 UTC, VitalyPeryatin commented on app/build.gradle
>      implementation 'androidx.core:core-ktx:1.7.0'
Подтяни код из `develop`

2022-08-30 17:01 UTC, productomar approved these changes
Узнал, что такое detekt

2022-08-30 19:21 UTC, grafgad approved these changes

2022-08-31 09:42 UTC, VitalyPeryatin requested changes

2022-08-31 09:42 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    # complexity: 2
Пустые комментарии в коде оставлять не надо. Надо разобраться нужны ли они нам, и если точно не нужны - удалить

2022-08-31 09:42 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +  # - 'PackageCountProcessor'
Точно нужны эти комментарии тут?

2022-08-31 09:42 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +  # - 'TxtOutputReport'
Точно ли нужны эти комментарии?

2022-08-31 09:42 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +  #  - 'LiteFindingsReport'
Точно ли нужны эти комментарии?

2022-08-31 09:42 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Точно тут `active: false`?

2022-08-31 09:42 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Точно тут `active: false`?

2022-08-31 09:42 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Точно тут `active: false`?

2022-08-31 09:42 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Точно тут `active: false`?

2022-08-31 09:42 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    active: false
Для всех случаев где поставил `active: false` опиши причину почему оставил именно такое правило для проекта

2022-08-31 12:13 UTC, Bittner322 commented on config/detekt/detekt.yml
> +    active: false
Это был дефолтный файл конфигурации, сам я ничего в false не ставил. Погуглив и подумав своими мозгами, я понял, что стоит их всех обратить в true. Все ваши замечания поправил, а также составил регулярное выражения для PackageNaming.

2022-09-01 18:32 UTC, grafgad submitted a review, later dismissed

2022-09-01 18:44 UTC, VitalyPeryatin commented on config/detekt/detekt.yml
> +    # style: 1
Комментарии не удалены

2022-09-02 06:40 UTC, VitalyPeryatin approved these changes

2022-09-02 09:46 UTC, grafgad approved these changes

2022-09-02 09:47 UTC, merged