Добавил переключение табов категорий и добавление категории, но есть небольшой баг
VitalyPeryatin/FinanceTracker pull request #59
Opened 2022-10-30 12:11 UTC by Bittner322

Баг заключается в том, что новая категория после доавбления появляется только после перезапуска

2022-10-30 16:39 UTC, VitalyPeryatin requested changes

2022-10-30 16:39 UTC, VitalyPeryatin commented on android/src/main/res/values/strings.xml
> +<resources>
Файла `strings.xml` по пути `android/src/main/res/values/strings.xml` не должно быть. Ресурсы лежат в папке common

2022-10-30 16:39 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/DragDropState.kt
> +                draggedDistance > 0 -> (endOffset - state.layoutInfo.viewportEndOffset + 0f).takeIf { diff -> diff > 0 }
Посмотри на что влияли эти 50f. Если не получится разобраться, то лучше оставить 50f на всякий случай

2022-10-30 16:39 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/LazyDragColumn.kt
> +                                topStart = 0.dp,
Параметры с `0dp` указывать в `RoundedCornerShape` не надо. Это лишний код

2022-10-30 16:39 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/LazyDragColumn.kt
> +                                bottomEnd = 0.dp
Тут тоже не надо `0dp` указывать

2022-10-30 16:39 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/navigation/main/MainNavigationGraph.kt
> +        AddCategoryScreen(appBarText = it as String)
А что тут в `it` передается? 
Ещё пугает force cast к String

2022-10-30 16:39 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/ExpenseIncomeTabs.kt
> +        text = getLocalizedString(categoryTab.textId, context),
Подтяни `develop`. Вместо `getLocalizedString` лучше использовать `stringResource` со строкой в параметрах

2022-10-30 16:39 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_category/AddCategoryAppBar.kt
> +                onClick = { rootController.findRootController().popBackStack() },
А здесь без `.findRootController()` не получится?

2022-10-30 16:39 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_category/AddCategoryAppBar.kt
> +                text = getLocalizedString(id = textValue, context = context),
`getLocalizedString` по возможности лучше не юзать, так как у него неудобно APi

2022-10-30 16:43 UTC, Bittner322 commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/navigation/main/MainNavigationGraph.kt
> +        AddCategoryScreen(appBarText = it as String)
Передается текст, который будет в TopAppBar экрана добавления категорий, в зависимости от таба: если таб Expense, то сверху будет "New Expense Category", если таб Income, то сверху будет "New Income Category"

2022-10-30 16:43 UTC, Bittner322 commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/navigation/main/MainNavigationGraph.kt
> +        AddCategoryScreen(appBarText = it as String)
Точнее не текст, а id текста

2022-10-31 14:59 UTC, VitalyPeryatin requested changes

2022-10-31 14:59 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/add_category/AddCategoryButton.kt
> +    modifier: Modifier = Modifier,
Modifier всегда пишется первым после всех аргументов, не имеющих дефолтное значение

2022-10-31 14:59 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/database/DatabaseInitializer.kt
> +            name = "Salary",
Если есть возможность, то лучше все категории по умолчанию добавлять внутри `sq` файла

2022-10-31 14:59 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/DragDropExt.kt
> +    val previous: Float by animateFloatAsState(dragDropState.previousItemOffset.value)
Актуализируй скриншоты в PR

2022-11-01 11:50 UTC, Bittner322 commented
<img width="435" alt="Снимок экрана 2022-11-01 в 17 48 32" src="https://user-images.githubusercontent.com/100136541/199226323-56f74192-28a9-4d34-8850-92b0506dc5cd.png">
<img width="384" alt="Снимок экрана 2022-11-01 в 17 48 58" src="https://user-images.githubusercontent.com/100136541/199226334-e9759349-e746-4a00-8cda-47b3f90fce0e.png">

2022-11-01 15:05 UTC, VitalyPeryatin approved these changes

2022-11-01 15:05 UTC, merged