feature/FT-6_add_Chucker
VitalyPeryatin/FinanceTracker pull request #6
Opened 2022-08-29 19:34 UTC by grafgad

2022-08-30 10:39 UTC, vitaliyche submitted a review, later dismissed

2022-08-30 11:08 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    debugImplementation("com.github.chuckerteam.chucker:library:3.5.2")
Вынеси версию chucker рядом с отдельную переменную `def`

2022-08-30 11:09 UTC, VitalyPeryatin requested changes

2022-08-30 11:09 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    releaseImplementation("com.github.chuckerteam.chucker:library-no-op:3.5.2")
Вынеси версию chucker рядом с отдельную переменную `def`

2022-08-30 19:47 UTC, grafgad commented on app/build.gradle.kts
> +    releaseImplementation("com.github.chuckerteam.chucker:library-no-op:3.5.2")
Исправил

Билд отказался запускаться, типа нашел одну зависимость в двух библиотеках вьюмодели. Вылечил подключением viewmodel-ktx.

2022-08-31 09:36 UTC, VitalyPeryatin submitted a review, later dismissed

2022-08-31 09:36 UTC, VitalyPeryatin commented
Ждём апрува от других членов команды

2022-09-01 15:02 UTC, VitalyPeryatin submitted a review, later dismissed

2022-09-01 15:03 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    debugImplementation("com.github.chuckerteam.chucker:library:${chukerVresion}")
Фигурные скобки тут не нужны. Это не критично, но лучше поправить

2022-09-01 18:25 UTC, grafgad commented on app/build.gradle.kts
> +    debugImplementation("com.github.chuckerteam.chucker:library:${chukerVresion}")
Готово.

2022-09-01 18:26 UTC, Bittner322 submitted a review, later dismissed

2022-09-01 18:45 UTC, VitalyPeryatin submitted a review, later dismissed

2022-09-01 18:54 UTC, vitaliyche submitted a review, later dismissed

2022-09-02 09:03 UTC, grafgad commented
сделал drop commit и вернул ViewModel

2022-09-02 11:27 UTC, Bittner322 approved these changes

2022-09-02 18:32 UTC, VitalyPeryatin approved these changes

2022-09-02 18:32 UTC, merged