feature/FT-9_release_obfuscation
VitalyPeryatin/FinanceTracker pull request #7
Opened 2022-08-30 20:19 UTC by grafgad

2022-08-31 09:34 UTC, VitalyPeryatin requested changes

2022-08-31 09:34 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1")
Изменений в dependencies быть не должно. Они должны быть в рамках другой задачи => в рамках другой ветки

2022-08-31 21:00 UTC, grafgad commented on app/build.gradle.kts
> +    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1")
Эти изменения связаны с Chucker и они там описана причина. Там же и отключил последним коммитом, но тогда получаю дубликат классов вьюмодели.

2022-09-01 15:01 UTC, VitalyPeryatin submitted a review, later dismissed

2022-09-01 18:26 UTC, Bittner322 submitted a review, later dismissed

2022-09-01 18:56 UTC, vitaliyche submitted a review, later dismissed

2022-09-02 09:40 UTC, grafgad commented
загрузил изменения из develop

2022-09-02 11:26 UTC, Bittner322 submitted a review, later dismissed

2022-09-02 18:36 UTC, VitalyPeryatin requested changes

2022-09-02 18:36 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    debugImplementation("com.github.chuckerteam.chucker:library:${chukerVresion}")
Подгрузи ещё разок изменения из develop. Все эти зависимости должны уже быть там

2022-09-03 05:38 UTC, VitalyPeryatin approved these changes

2022-09-03 05:39 UTC, VitalyPeryatin approved these changes

2022-09-03 07:06 UTC, Bittner322 submitted a review, later dismissed

2022-09-03 08:50 UTC, vitaliyche approved these changes

2022-09-03 10:30 UTC, closed without merging