FT-63: Implement settings bottom dialog
VitalyPeryatin/FinanceTracker pull request #72
Opened 2022-11-05 15:18 UTC by Bittner322

Есть проблемы с рипплами, не знаю как их адекватно сделать

2022-11-05 15:18 UTC, Bittner322 commented
<img width="472" alt="Снимок экрана 2022-11-05 в 21 17 29" src="https://user-images.githubusercontent.com/100136541/200126988-21275d08-83f4-4719-9c3c-6423d42d0a17.png">

2022-11-05 15:46 UTC, VitalyPeryatin requested changes

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/HomeTopBar.kt
> +    val bottomDialog = ModalSheetConfiguration(cornerRadius = 12)
Это скорее `sheetConfiguration`, чем полноценный `bottomDialog`

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/HomeTopBar.kt
> +                            SettingsSheet (
Форматирование

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/home/HomeScreen.kt
> +                .navigationBarsPadding()
Если подряд идут сразу `statusBarsPadding` и `navigationBarsPadding`, то лучше заменить оба на `systemBarsPadding`. Заранее стоит отдельно прописать expect/actual для этой новой функции аналогично функции `navigationBarsPadding`

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +            modifier = Modifier
В корневом Composable должен использоваться `modifier` из параметра функции

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +                        bottom = 16.dp
Пропиши ещё боковые оnстутпы: 
```
.padding(
    vertical = 16.dp,
    horizontal = 12.dp
)
```
Это выручит, когда приложение будет локализовываться на другие языки, и в каком-то из языков слово "Settings" будет слишком длинным

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +            Row(
В отдельную Compose функцию лучше вынести, чтобы было читаемее

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +            Row(
В отдельную Compose функцию лучше вынести, чтобы было читаемее

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +                )
Не учел отступ в конце строки. Он должен быть равен отступу перед иконкой на случай если строка будет слишком длинной. 
Я бы просто у `Row` задал бы отступы `horizontal = 16.dp`

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +                    .height(24.dp)
Никогда не ограничивай по высоте контейнеры в котором содержится текст. Иначе потом увеличенный через настройки текст будет обрезаться. Смотрится это так себе

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +                Spacer(Modifier.weight(1f))
`Spacer` лишний

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +                    style = CoinTheme.typography.body1
Не учел отступ в конце текста

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +                CurrencySelector(
У `CurrencySelector` некорректное смещение. `popup` должен открываться с небольшим по вертикали отступом над кнопкой с выравниванием по правой стороне кнопки и попапа

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +                    .height(24.dp)
Никогда не ограничивай по высоте контейнеры в котором содержится текст

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +                    .clickable {
Чтобы не было проблем с ripple эффектом (то есть чтобы ripple эффект учитывал отступы), то `padding` нужно писать под `clickable`

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +                    .padding(bottom = 20.dp)
Когда уберешь `padding` под `clickable` надо будет в `padding` под `clickable` использовать `vertical` параметр

2022-11-05 15:46 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsSheet.kt
> +                    .padding(bottom = 20.dp)
Тут если хочется не учитывать ripple эффект у кнопки, то лучше проставить padding у родительского элемента, так как имеется ввиду скорее то, чтобы ripple эффект не достигал самого конца диалога, а не то, чтобы именно у этой кнопки был такой большой отступ снизу и при этом не учитывался ripple эффектом

2022-11-06 11:08 UTC, Bittner322 commented
<img width="455" alt="Снимок экрана 2022-11-06 в 17 07 01" src="https://user-images.githubusercontent.com/100136541/200167182-bf30e840-555e-4156-a4fc-eb68a4a61691.png">

2022-11-06 13:15 UTC, VitalyPeryatin requested changes

2022-11-06 13:15 UTC, VitalyPeryatin commented on common/src/commonMain/resources/drawable/ic_dollar.xml
> +  <path
Не очень понял зачем тут иконка доллара? У валюты всегда есть какой-то UTF-8 символ на сколько я знаю

2022-11-06 13:15 UTC, VitalyPeryatin commented on common/src/commonMain/resources/drawable/ic_categories_settings.xml
> +      android:fillAlpha="0.6"/>
У иконки по умолчанию не должна бать задана прозрачность, чтобы эту иконки было проще переиспользовать. Лучше при использовании иконки отдельно задавать `tint`

2022-11-06 15:56 UTC, VitalyPeryatin approved these changes

2022-11-06 15:56 UTC, merged