feature/FT-10_jetpack_compose
VitalyPeryatin/FinanceTracker pull request #8
Opened 2022-09-02 10:42 UTC by grafgad

Подключил по руководству, но, мне кажется, что часть лишняя.

2022-09-02 11:26 UTC, Bittner322 submitted a review, later dismissed

2022-09-02 18:50 UTC, VitalyPeryatin requested changes

2022-09-02 18:50 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    val composeVersion = "1.2.1"
Нужна версия `1.3.0-beta01`, так как начиная с нее поддерживается Android 13 (+ там много фиксов и приятных оптимизаций). А мы в проекте изначально поддерживаем Android 13

2022-09-02 18:50 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    implementation("androidx.compose.ui:ui:${composeVersion}")
Часть либ действительно лишние. Нам не понадобятся в ближайшее время: 
- implementation("androidx.compose.runtime:runtime-livedata:${composeVersion}")
- implementation("androidx.compose.material:material-icons-core:${composeVersion}")

2022-09-02 18:50 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    val chukerVersion = "3.5.2"
Эти зависимости и ниже уже есть в develop. Нужно актуализировать ветку

2022-09-02 18:50 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    // Material Design
Конкретно каждую зависимость комментировать не стоит. Достаточно один собирательный коммент оставить. Например `// Compose`

2022-09-02 18:50 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    implementation("androidx.compose.animation:animation:${composeVersion}")
Фигурный скобки рядом с версией лишние

2022-09-03 05:43 UTC, VitalyPeryatin approved these changes

2022-09-03 07:05 UTC, Bittner322 approved these changes

2022-09-03 08:51 UTC, vitaliyche approved these changes

2022-09-03 10:10 UTC, merged