feature/FT-11_Firebase_Crashlytics
VitalyPeryatin/FinanceTracker pull request #9
Opened 2022-09-03 10:57 UTC by grafgad

2022-09-03 11:47 UTC, Bittner322 submitted a review, later dismissed

2022-09-03 14:37 UTC, VitalyPeryatin requested changes

2022-09-03 14:37 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +        getByName("debug") {
Зачем использовать `getByName("debug")`, если можно написать просто `debug`? 
Возможно, я что-то не знаю

2022-09-03 14:37 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    // When using the BoM, don"t specify versions in Firebase dependencies
Этот комментарий здесь не нужен

2022-09-03 14:37 UTC, VitalyPeryatin commented on app/build.gradle.kts
> +    // UI Tests
О, молодец, что привел все комментарии к единому стилю

2022-09-03 14:37 UTC, VitalyPeryatin commented on app/src/main/java/com/finance_tracker/finance_tracker/MainActivity.kt
> +        val crashButton = Button(this)
На View компонентам не пишем сейчас. 
Этот тестовый код , вызывающий краш нужно удалить

2022-09-04 05:32 UTC, VitalyPeryatin approved these changes

2022-09-04 19:03 UTC, Bittner322 approved these changes

2022-09-05 03:47 UTC, merged